name: Hello Natixis

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
         echo "Obtendo código..."
      - name: Install dependencies
        run: |
         echo "Instalando dependências..."
      - name: Run tests
        run: |
         echo "Rodando testes..." 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        run: |
         echo "Obtendo código..."
      - name: Install dependencies
        run: |
         echo "Instalando dependências..."
      - name: Run tests
        run: |
         echo "Rodando testes..." 
         